[project]
name = "curso-analisis-datos"
version = "0.1.0"
description = "Proyecto integrador del curso Programacion en Entornos de Datos"
readme = "README.md"
requires-python = ">=3.11"
license = { text = "MIT" }
dependencies = [
    "pandas>=2.2",
    "numpy>=1.26",
    "dlt[duckdb]>=1.0",
    "duckdb>=1.0",
    "dbt-core>=1.8",
    "dbt-duckdb>=1.8",
    "dagster>=1.8",
    "dagster-dbt>=0.24",
    "dagster-webserver>=1.8",
    "psycopg2-binary"
]

[dependency-groups]
dev = [
    "pytest>=8.0",
    "ruff>=0.6",
    "jupyterlab>=4.2",
]

[tool.ruff]
line-length = 100
target-version = "py311"

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["src", "data"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"